DEFAULT_GOAL: build

build:
	docker build . -t liampetch/devopsjourneychallenge2:latest

run:
	docker run -it -p 8080:80 liampetch/devopsjourneychallenge2

push:
	docker push liampetch/devopsjourneychallenge2
