DEFAULT_GOAL: build

build:
	docker build . -t liampetch/devopsjourneychallenge1:latest

run:
	docker run -it -p 8080:80 liampetch/devopsjourneychallenge1

push:
	docker push liampetch/devopsjourneychallenge1
